<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<nav class="indigo darken-4">
    <div class="navwrapper">
        <ul>
            <li><?php echo Html::link('usuarios/registrar','Registrar') ?></li>
            <li><?php echo Html::link('usuarios','Lista de usuarios') ?></li>
        </ul>
    </div>
</nav>

</body>
</html>